-- 코드를 작성해주세요
SELECT SUM(TMP) AS FISH_COUNT
FROM (
select COUNT(FISH_TYPE) AS TMP
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING FISH_TYPE = (SELECT FISH_TYPE FROM FISH_NAME_INFO
                     WHERE FISH_NAME='BASS')
        OR
        FISH_TYPE = (SELECT FISH_TYPE FROM FISH_NAME_INFO
                     WHERE FISH_NAME='SNAPPER')) AS TMP;